import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const pageSource = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");

test("baseline type is operator context and is not added to the API payload", () => {
  assert.match(pageSource, /useState<BaselineType>\("working"\)/);
  assert.match(pageSource, /Observed baseline/);
  assert.match(pageSource, /Working assumption/);
  assert.match(pageSource, /<option value="unknown">Unknown<\/option>/);
  assert.doesNotMatch(pageSource, /baseline_type:\s*(?:baselineType|values\.)/);
});

test("baseline and expected conversion use the clarified language", () => {
  assert.match(pageSource, /inputLabel="Baseline conversion"/);
  assert.match(pageSource, /helper="What conversion rate are we starting from\?"/);
  assert.match(pageSource, /Your experiment hypothesis — not a prediction generated by the system\./);
  assert.match(pageSource, /Why do you believe this outcome is achievable\?/);
});

test("decision presentation is scoped to running the experiment", () => {
  assert.match(pageSource, /return "Run the experiment\."/);
  assert.match(pageSource, /return "Refine or validate the assumptions before running\."/);
  assert.match(pageSource, /return "Do not run this experiment under the current assumptions\."/);
  assert.match(pageSource, /<p>Next step<\/p>/);
});

test("editing assumptions or context invalidates a stale simulation", () => {
  assert.match(pageSource, /function invalidateSimulation\(\)/);
  assert.match(
    pageSource,
    /function updateValue[\s\S]*?setValues[\s\S]*?invalidateSimulation\(\)/,
  );
  assert.match(
    pageSource,
    /setContext\(parsed\.context\)[\s\S]*?invalidateSimulation\(\)/,
  );
});

test("unreachable break-even conversion is labelled explicitly", () => {
  assert.match(pageSource, /value > 1 \? `Not achievable \(\$\{percentage\} required\)`/);
  assert.match(
    pageSource,
    /formatBreakEvenRate\(result\.break_even_expected_conversion_rate\)/,
  );
});

test("successful imports and context clearing reset the operator rationale", () => {
  assert.match(
    pageSource,
    /setContext\(parsed\.context\)[\s\S]*?setRationale\(""\)[\s\S]*?invalidateSimulation\(\)/,
  );
  assert.match(
    pageSource,
    /function clearOpportunity\(\)[\s\S]*?setRationale\(""\)[\s\S]*?invalidateSimulation\(\)/,
  );
});

test("structured Agent imports do not fabricate operator assumptions", () => {
  assert.match(pageSource, /const EMPTY_IMPORTED_VALUES:[\s\S]*?pilot_size: ""/);
  assert.match(pageSource, /current_conversion_rate: ""/);
  assert.match(pageSource, /expected_conversion_rate: ""/);
  assert.match(pageSource, /evidence_confidence: ""/);
  assert.match(pageSource, /feasibility: ""/);
  assert.match(
    pageSource,
    /setContext\(parsed\.context\)[\s\S]*?setValues\(EMPTY_IMPORTED_VALUES\)[\s\S]*?setBaselineType\("unknown"\)/,
  );
  assert.match(pageSource, /Baseline not established — operator assumption required\./);
  assert.match(pageSource, /Expected outcome not established — operator assumption required\./);
  assert.match(pageSource, /Evidence confidence not set/);
});

test("evaluation waits for explicit operator assumptions", () => {
  assert.match(pageSource, /REQUIRED_ASSUMPTION_FIELDS\.every/);
  assert.match(pageSource, /!assumptionsComplete \|\| !rationale\.trim\(\)/);
  assert.match(pageSource, /Confidence and feasibility are operator judgments\./);
});

test("the importer displays the parser's specific validation message", () => {
  assert.match(pageSource, /setImportError\(opportunityParseErrorMessage\(parsed\)\)/);
});
